package com.keplerops.groundcontrol.domain.graph.model;

public enum GraphEntityType {
    REQUIREMENT,
    OPERATIONAL_ASSET,
    OBSERVATION,
    RISK_SCENARIO,
    RISK_REGISTER_RECORD,
    RISK_ASSESSMENT_RESULT,
    TREATMENT_PLAN,
    METHODOLOGY_PROFILE,
    CONTROL,
    CONTROL_LINK,
    CONTROL_TEST,
    CONTROL_EFFECTIVENESS_ASSESSMENT,
    VERIFICATION_RESULT,
    THREAT_MODEL,
    FINDING,
    EVIDENCE_ARTIFACT,
    AUDIT,
    AUDIT_LINK
}
