name: Quality Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev

      - name: Check trailing whitespace and file endings
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: trailing-whitespace end-of-file-fixer --all-files

      - name: Run isort
        run: poetry run isort . --check-only --diff --profile black

      - name: Run Black
        run: poetry run black . --check --diff

      - name: Run Flake8
        run: |
          poetry run flake8 . \
            --max-line-length=100 \
            --extend-ignore=E203,W503 \
            --exclude=.git,__pycache__,build,dist \
            --per-file-ignores="__init__.py:F401 tests/*:D100,D101,D102,D103" \
            --docstring-convention=google
